// source: backend_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.backend.CreateNewSpeciesRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.backend.GenomeInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.backend.CreateNewSpeciesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.backend.CreateNewSpeciesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.backend.CreateNewSpeciesRequest.displayName = 'proto.backend.CreateNewSpeciesRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.backend.CreateNewSpeciesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.backend.CreateNewSpeciesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.backend.CreateNewSpeciesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.CreateNewSpeciesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    speciesname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    initialgenome: (f = msg.getInitialgenome()) && proto.backend.GenomeInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.backend.CreateNewSpeciesRequest}
 */
proto.backend.CreateNewSpeciesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.backend.CreateNewSpeciesRequest;
  return proto.backend.CreateNewSpeciesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.backend.CreateNewSpeciesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.backend.CreateNewSpeciesRequest}
 */
proto.backend.CreateNewSpeciesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpeciesname(value);
      break;
    case 2:
      var value = new proto.backend.GenomeInfo;
      reader.readMessage(value,proto.backend.GenomeInfo.deserializeBinaryFromReader);
      msg.setInitialgenome(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.backend.CreateNewSpeciesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.backend.CreateNewSpeciesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.backend.CreateNewSpeciesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.CreateNewSpeciesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpeciesname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInitialgenome();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.backend.GenomeInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string speciesName = 1;
 * @return {string}
 */
proto.backend.CreateNewSpeciesRequest.prototype.getSpeciesname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.backend.CreateNewSpeciesRequest} returns this
 */
proto.backend.CreateNewSpeciesRequest.prototype.setSpeciesname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GenomeInfo initialGenome = 2;
 * @return {?proto.backend.GenomeInfo}
 */
proto.backend.CreateNewSpeciesRequest.prototype.getInitialgenome = function() {
  return /** @type{?proto.backend.GenomeInfo} */ (
    jspb.Message.getWrapperField(this, proto.backend.GenomeInfo, 2));
};


/**
 * @param {?proto.backend.GenomeInfo|undefined} value
 * @return {!proto.backend.CreateNewSpeciesRequest} returns this
*/
proto.backend.CreateNewSpeciesRequest.prototype.setInitialgenome = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.backend.CreateNewSpeciesRequest} returns this
 */
proto.backend.CreateNewSpeciesRequest.prototype.clearInitialgenome = function() {
  return this.setInitialgenome(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.backend.CreateNewSpeciesRequest.prototype.hasInitialgenome = function() {
  return jspb.Message.getField(this, 2) != null;
};


