// source: backend_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.backend.CreatureInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.backend.GenomeInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.backend.CreatureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.backend.CreatureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.backend.CreatureInfo.displayName = 'proto.backend.CreatureInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.backend.CreatureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.backend.CreatureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.backend.CreatureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.CreatureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    species: jspb.Message.getFieldWithDefault(msg, 2, ""),
    xcoordinate: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    ycoordinate: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    genome: (f = msg.getGenome()) && proto.backend.GenomeInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.backend.CreatureInfo}
 */
proto.backend.CreatureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.backend.CreatureInfo;
  return proto.backend.CreatureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.backend.CreatureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.backend.CreatureInfo}
 */
proto.backend.CreatureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpecies(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setXcoordinate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setYcoordinate(value);
      break;
    case 5:
      var value = new proto.backend.GenomeInfo;
      reader.readMessage(value,proto.backend.GenomeInfo.deserializeBinaryFromReader);
      msg.setGenome(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.backend.CreatureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.backend.CreatureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.backend.CreatureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.CreatureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSpecies();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getXcoordinate();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getYcoordinate();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getGenome();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.backend.GenomeInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.backend.CreatureInfo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.backend.CreatureInfo} returns this
 */
proto.backend.CreatureInfo.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string species = 2;
 * @return {string}
 */
proto.backend.CreatureInfo.prototype.getSpecies = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.backend.CreatureInfo} returns this
 */
proto.backend.CreatureInfo.prototype.setSpecies = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float xCoordinate = 3;
 * @return {number}
 */
proto.backend.CreatureInfo.prototype.getXcoordinate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.backend.CreatureInfo} returns this
 */
proto.backend.CreatureInfo.prototype.setXcoordinate = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float yCoordinate = 4;
 * @return {number}
 */
proto.backend.CreatureInfo.prototype.getYcoordinate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.backend.CreatureInfo} returns this
 */
proto.backend.CreatureInfo.prototype.setYcoordinate = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional GenomeInfo genome = 5;
 * @return {?proto.backend.GenomeInfo}
 */
proto.backend.CreatureInfo.prototype.getGenome = function() {
  return /** @type{?proto.backend.GenomeInfo} */ (
    jspb.Message.getWrapperField(this, proto.backend.GenomeInfo, 5));
};


/**
 * @param {?proto.backend.GenomeInfo|undefined} value
 * @return {!proto.backend.CreatureInfo} returns this
*/
proto.backend.CreatureInfo.prototype.setGenome = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.backend.CreatureInfo} returns this
 */
proto.backend.CreatureInfo.prototype.clearGenome = function() {
  return this.setGenome(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.backend.CreatureInfo.prototype.hasGenome = function() {
  return jspb.Message.getField(this, 5) != null;
};


