// source: backend_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.backend.GetEnvironmentInfoReply');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.backend.CreatureAnimationInfo');
goog.require('proto.backend.ElevationInfo');
goog.require('proto.backend.ResourceInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.backend.GetEnvironmentInfoReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.backend.GetEnvironmentInfoReply.repeatedFields_, null);
};
goog.inherits(proto.backend.GetEnvironmentInfoReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.backend.GetEnvironmentInfoReply.displayName = 'proto.backend.GetEnvironmentInfoReply';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.backend.GetEnvironmentInfoReply.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.backend.GetEnvironmentInfoReply.prototype.toObject = function(opt_includeInstance) {
  return proto.backend.GetEnvironmentInfoReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.backend.GetEnvironmentInfoReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.GetEnvironmentInfoReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    creaturesList: jspb.Message.toObjectList(msg.getCreaturesList(),
    proto.backend.CreatureAnimationInfo.toObject, includeInstance),
    resourcesList: jspb.Message.toObjectList(msg.getResourcesList(),
    proto.backend.ResourceInfo.toObject, includeInstance),
    elevationList: jspb.Message.toObjectList(msg.getElevationList(),
    proto.backend.ElevationInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.backend.GetEnvironmentInfoReply}
 */
proto.backend.GetEnvironmentInfoReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.backend.GetEnvironmentInfoReply;
  return proto.backend.GetEnvironmentInfoReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.backend.GetEnvironmentInfoReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.backend.GetEnvironmentInfoReply}
 */
proto.backend.GetEnvironmentInfoReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.backend.CreatureAnimationInfo;
      reader.readMessage(value,proto.backend.CreatureAnimationInfo.deserializeBinaryFromReader);
      msg.addCreatures(value);
      break;
    case 2:
      var value = new proto.backend.ResourceInfo;
      reader.readMessage(value,proto.backend.ResourceInfo.deserializeBinaryFromReader);
      msg.addResources(value);
      break;
    case 3:
      var value = new proto.backend.ElevationInfo;
      reader.readMessage(value,proto.backend.ElevationInfo.deserializeBinaryFromReader);
      msg.addElevation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.backend.GetEnvironmentInfoReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.backend.GetEnvironmentInfoReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.backend.GetEnvironmentInfoReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.GetEnvironmentInfoReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreaturesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.backend.CreatureAnimationInfo.serializeBinaryToWriter
    );
  }
  f = message.getResourcesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.backend.ResourceInfo.serializeBinaryToWriter
    );
  }
  f = message.getElevationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.backend.ElevationInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CreatureAnimationInfo creatures = 1;
 * @return {!Array<!proto.backend.CreatureAnimationInfo>}
 */
proto.backend.GetEnvironmentInfoReply.prototype.getCreaturesList = function() {
  return /** @type{!Array<!proto.backend.CreatureAnimationInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.backend.CreatureAnimationInfo, 1));
};


/**
 * @param {!Array<!proto.backend.CreatureAnimationInfo>} value
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
*/
proto.backend.GetEnvironmentInfoReply.prototype.setCreaturesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.backend.CreatureAnimationInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.backend.CreatureAnimationInfo}
 */
proto.backend.GetEnvironmentInfoReply.prototype.addCreatures = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.backend.CreatureAnimationInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
 */
proto.backend.GetEnvironmentInfoReply.prototype.clearCreaturesList = function() {
  return this.setCreaturesList([]);
};


/**
 * repeated ResourceInfo resources = 2;
 * @return {!Array<!proto.backend.ResourceInfo>}
 */
proto.backend.GetEnvironmentInfoReply.prototype.getResourcesList = function() {
  return /** @type{!Array<!proto.backend.ResourceInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.backend.ResourceInfo, 2));
};


/**
 * @param {!Array<!proto.backend.ResourceInfo>} value
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
*/
proto.backend.GetEnvironmentInfoReply.prototype.setResourcesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.backend.ResourceInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.backend.ResourceInfo}
 */
proto.backend.GetEnvironmentInfoReply.prototype.addResources = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.backend.ResourceInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
 */
proto.backend.GetEnvironmentInfoReply.prototype.clearResourcesList = function() {
  return this.setResourcesList([]);
};


/**
 * repeated ElevationInfo elevation = 3;
 * @return {!Array<!proto.backend.ElevationInfo>}
 */
proto.backend.GetEnvironmentInfoReply.prototype.getElevationList = function() {
  return /** @type{!Array<!proto.backend.ElevationInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.backend.ElevationInfo, 3));
};


/**
 * @param {!Array<!proto.backend.ElevationInfo>} value
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
*/
proto.backend.GetEnvironmentInfoReply.prototype.setElevationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.backend.ElevationInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.backend.ElevationInfo}
 */
proto.backend.GetEnvironmentInfoReply.prototype.addElevation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.backend.ElevationInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.backend.GetEnvironmentInfoReply} returns this
 */
proto.backend.GetEnvironmentInfoReply.prototype.clearElevationList = function() {
  return this.setElevationList([]);
};


