// source: backend_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.backend.SpeciesInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.backend.CreatureInfo');
goog.require('proto.backend.GenomeInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.backend.SpeciesInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.backend.SpeciesInfo.repeatedFields_, null);
};
goog.inherits(proto.backend.SpeciesInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.backend.SpeciesInfo.displayName = 'proto.backend.SpeciesInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.backend.SpeciesInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.backend.SpeciesInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.backend.SpeciesInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.backend.SpeciesInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.SpeciesInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    speciesname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    genometemplate: (f = msg.getGenometemplate()) && proto.backend.GenomeInfo.toObject(includeInstance, f),
    creaturesList: jspb.Message.toObjectList(msg.getCreaturesList(),
    proto.backend.CreatureInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.backend.SpeciesInfo}
 */
proto.backend.SpeciesInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.backend.SpeciesInfo;
  return proto.backend.SpeciesInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.backend.SpeciesInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.backend.SpeciesInfo}
 */
proto.backend.SpeciesInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpeciesname(value);
      break;
    case 2:
      var value = new proto.backend.GenomeInfo;
      reader.readMessage(value,proto.backend.GenomeInfo.deserializeBinaryFromReader);
      msg.setGenometemplate(value);
      break;
    case 3:
      var value = new proto.backend.CreatureInfo;
      reader.readMessage(value,proto.backend.CreatureInfo.deserializeBinaryFromReader);
      msg.addCreatures(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.backend.SpeciesInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.backend.SpeciesInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.backend.SpeciesInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.backend.SpeciesInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpeciesname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGenometemplate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.backend.GenomeInfo.serializeBinaryToWriter
    );
  }
  f = message.getCreaturesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.backend.CreatureInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string speciesName = 1;
 * @return {string}
 */
proto.backend.SpeciesInfo.prototype.getSpeciesname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.backend.SpeciesInfo} returns this
 */
proto.backend.SpeciesInfo.prototype.setSpeciesname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional GenomeInfo genomeTemplate = 2;
 * @return {?proto.backend.GenomeInfo}
 */
proto.backend.SpeciesInfo.prototype.getGenometemplate = function() {
  return /** @type{?proto.backend.GenomeInfo} */ (
    jspb.Message.getWrapperField(this, proto.backend.GenomeInfo, 2));
};


/**
 * @param {?proto.backend.GenomeInfo|undefined} value
 * @return {!proto.backend.SpeciesInfo} returns this
*/
proto.backend.SpeciesInfo.prototype.setGenometemplate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.backend.SpeciesInfo} returns this
 */
proto.backend.SpeciesInfo.prototype.clearGenometemplate = function() {
  return this.setGenometemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.backend.SpeciesInfo.prototype.hasGenometemplate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated CreatureInfo creatures = 3;
 * @return {!Array<!proto.backend.CreatureInfo>}
 */
proto.backend.SpeciesInfo.prototype.getCreaturesList = function() {
  return /** @type{!Array<!proto.backend.CreatureInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.backend.CreatureInfo, 3));
};


/**
 * @param {!Array<!proto.backend.CreatureInfo>} value
 * @return {!proto.backend.SpeciesInfo} returns this
*/
proto.backend.SpeciesInfo.prototype.setCreaturesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.backend.CreatureInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.backend.CreatureInfo}
 */
proto.backend.SpeciesInfo.prototype.addCreatures = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.backend.CreatureInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.backend.SpeciesInfo} returns this
 */
proto.backend.SpeciesInfo.prototype.clearCreaturesList = function() {
  return this.setCreaturesList([]);
};


